permalinks: title
markdown: kramdown
pygments: true
baseurl: /python-data-intro
title: Introduction to Data Processing with Python
map:
 - title: Home
   path: /
   caption: Introduction to Data Processing with Python
 - title: Core
   caption: The 'mandatory' workshop content
   subpages:
     - title: Recap of Python essentials
       path: /core/recap.html
       caption: A quick recap of some of the Introduction to Programming essentials
     - title: Data Structures in Python
       path: /core/data.html
       caption: An introduction to the list and dictionary data structures.
     - title: Introducing IPython Notebook
       path: /core/notebook.html
       caption: A whole new way to work with Python!
     - title: Working With Text Files
       path: /core/text-files.html
       caption: What is a text file? How do we get them in and out of Python?
     - title: Working With Strings
       path: /core/strings.html
       caption: Once we have our text in Python, what can we do with it?
     - title: Creating Charts
       path: /core/charts.html
       caption: Using IPython Notebook with matplotlib to create charts.
     - title: CSV Files
       path: /core/csv.html
       caption: Reading comma-separated data.
 - title: Extras
   caption: Additional workshop content
   subpages:
   - title: Alternative Approaches
     path: /extras/alternatives.html
     caption: Some other ways to store and process data.
   - title: Open Data
     path: /extras/opendata.html
     caption: Some places to find open data sets.
